dubbo:
  application:
    name: dubbo-provider
    qos-enable: true
    qos-port: 33333
    qos-accept-foreign-ip: false
  registry:
    address: zookeeper://192.168.31.91:2181
    timeout: 50000
    parameters:
      blockUntilConnectedWait: 50
  protocol:
    name: dubbo
    port: 20881
    host: 192.168.31.41
  provider:
    timeout: 5000
    retries: 0
  scan:
    base-packages: com.ck.provider.service

server:
  port: 8080

logging:
  level:
    com.ck: DEBUG
    org.apache.dubbo: INFO
